# A first workflow to play around with the editor
name: My First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - run:  |
          echo "Hello world from ${{ github.actor }}."
          echo "Curernt branch is '${{ github.ref }}'."
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - run: tree
      
        
